# Dependencies
markdown:            Kramdown
highlighter:         rouge
# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:            Secret Garden
tagline:          'Let memory blossom with fragrance'
description:      'For personal archiving.'
url:              http://lilygeek.github.io

author:
  name:           'Li Liu'
  url:            http://lilygeek.github.io
  linkedin:       https://www.linkedin.com/in/%E7%AB%8B-%E5%88%98-70bb62102/
  photo:          /public/imgs/avatar.JPG
  introduction:   'Graduated from the School of Software at Tsinghua University. Now persuing PhD degree in Computer Science and Engineering at Michigan State University.'

paginate:         5
paginate_path:    '/blog/page:num'

# Custom vars
version:          1.0.0

